### PR TITLE
Fix qup/quc scanning

### PR DESCRIPTION
**Pull request by jameshalgren**
There was shift of 1 in the indexing of the upstream value passing.

### CODE REVIEW

**Comment by jameshalgren** [comment]
@jdhondia-noaa 
This now works with any of the other domains -- if you pass the `-n` flag plus a domain name, e.g., `Mainstems_CONUS`. There is now a flag for `--number_of_timesteps` and for length of `--time-step` in seconds. 

__NOTE:__ To run the test, pass the `--test` flag, i.e., 
```
python compute_nhd_routing_SingleSeg.py --test -v
```

**Comment by jameshalgren** [comment]
@jdhondia-noaa 
When (if) you merge this pull request with your branch, it will queue the changes into your already-existing pull request and we can review those changes all-together before bringing them into the main upstream repository. Please reach out with any questions. Thanks!

**Review by jdhondia-noaa — APPROVED** [review]
approach with list accessing previous and current values by james is correct

**Comment by jdhondia-noaa** [comment]
manually merged

**Pull request closed without merging**
